### ISSUE TITLE
Create the Preliminary SRD for Nucleus

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#6] opened 2022-04-08 01:10 UTC

**Comment by jordanpadams** [comment] 2022-05-04 21:21
duplicate of #5

**Comment by jordanpadams** [comment] 2022-07-02 20:07
Initial requirements defined: https://github.com/NASA-PDS/nucleus/blob/main/docs/requirements/REQUIREMENTS.md

**Closed by jordanpadams** 2022-07-02 20:07 UTC
Labels: B13.0, skip-i&t, task

**Comment by jordanpadams** [comment] 2022-07-02 20:10
duplicate of #5
